### PR TITLE
Screenshot tests suite

### PR DESCRIPTION
**Pull request by CherryPerry**
## Description

Plugin to run screenshot tests.

How to use:
1. Apply `id("appyx-screenshots")` in `build.gradle.kts`
2. Use the following structure for tests:
```kotlin
@get:Rule
val nameRule = TestName()

@Test
fun test() {
   bitmap.writeToTestStorage("${javaClass.simpleName}_${nameRule.methodName}")
}
```
3. Run either `screenshotTestsCompareBaseline` or `screenshotTestsRecordBaseline` task.

Requirements: `nodejs`, `npm`, `npx`

## Check list

- [x] I have updated `CHANGELOG.md` if required.
- [x] I have updated documentation if required.

### CODE REVIEW

**Comment by LachlanMcKee** [comment]
Why not use paparazzi? This seems like it will be quite a lot slower unfortunately

**Comment by LachlanMcKee** [comment]
I had attempted to do this here: https://github.com/bumble-tech/appyx/pull/244

**Comment by CherryPerry** [comment]
@vladcipariu91 asked for real screenshots because paparazzi did not work for his case.

**Comment by LachlanMcKee** [comment]
It would be good to discuss what the problem is. perhaps it's the same problem I faced?

**Comment by vladcipariu91** [comment]
as discussed with @LachlanMcKee we can merge this and look into a fix for Paparazzi later

**Pull request merged**
